# 配置文件加密key
jasypt:
  encryptor:
    password: monkeyzi
server:
  port: 8787
spring:
  application:
    name: rocketmq-api-pro
  # 数据库
  datasource:
        url: jdbc:mysql://monkeyzi:3306/monkeyboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: guoguo
        password: ENC(ly6ALRqFlY9vVwnabWCg+5j/J7PdUuHe)
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
  #exception
  mvc:
      throw-exception-if-no-handler-found: true
  resources:
      add-mappings: false


#mybatis plus配置
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      # 主键类型  AUTO(0),NONE(1),INPUT(2),ID_WORKER(3),UUID(4),ID_WORKER_STR(5);
      id-type: auto
      # 逻辑删除配置（下面3个配置）使用的时候在字段上加上@TableLogic  0默认不删除  1删除
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 数据库类型
      db-type: mysql
      #字段验证策略  默认也是NOT_NULL
      field-strategy: default
    # 关闭mp banner 启动的时候不让在控制台打印
    banner: false
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    #开发驼峰命名转化
    map-underscore-to-camel-case: true
    # 是否开启缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 打印sql
  #别名
  type-aliases-package: com.monkeyzi.rocketmq.entity


#rocketmq配置
mq:
  #namasrv地址
  nameSrvAddr: monkeyzi-mq:9876
  producer:
      #消息发送失败重发次数
      retryTimesWhenSendFailed: 3
      #消息发送超时时间
      sendMsgTimeOut: 3000
      #消息生产者组
      groupName: producer_group
  consumer:
      #最小的消费线程数
      consumeThreadMin: 10
      #最大的消费线程数
      consumeThreadMax: 50
      #消息消费者组
      groupName: comsumer_group
